services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: idempotency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
      
  grafana:
    image: grafana/otel-lgtm:0.11.4
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
